/*
 * SpoonacularAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cs301rclass.com.mashape.p.spoonacularrecipefoodnutritionv1.http.client;

import java.util.List;

import cs301rclass.com.mashape.p.spoonacularrecipefoodnutritionv1.http.client.HttpContext;
import cs301rclass.com.mashape.p.spoonacularrecipefoodnutritionv1.http.response.HttpResponse;
import cs301rclass.com.mashape.p.spoonacularrecipefoodnutritionv1.models.FindByIngredientsModel;

/**
 * Callback class for handling API calls with a templated response type T
 */
public interface APICallBack<T> {
    /**
     * On Completed callback for API calls
     * @param context   The context of the API request
     * @param response  The response received from the API Call
     */
//    public void onSuccess(HttpContext context, T response);

    void onSuccess(HttpContext context, HttpResponse response);

    /**
     * On Completed callback for API calls
     * @param context   The context of the API request
     * @param error Any error detected during the API Call and/or deserialization
     */
    public void onFailure(HttpContext context, Throwable error);
}